
<body style="min-width:372px;">
    <div class="d-flex flex-column wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark bg-danger border-bottom shadow-sm mb-3">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <strong>Quitanda Online</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a href="/" class="nav-link text-white">Principal</a>
                        </li>
                        <li class="nav-item">
                            <a href="/" class="nav-link text-white">Contato</a>
                        </li>
                    </ul>
                    <div class="align-self-end">
                        <ul class="navbar-nav">
                            
                            <li class="nav-item">
                                <a href="/login" class="nav-link text-white">Entrar</a>
                            </li>
                           
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        <main class="flex-fill">
        
            <div class="container">
            <?php if($this->view->erroCadastro){ ?>
                        <small class="form-text text-danger ">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>
                    <?php } ?> 

                <h1>Informe seus dados, por favor</h1>
                <hr>
                <form  id="form" method="post" class="mt-3">
                    <div class="row">
                        <div class="col-sm-12 col-md-6">
                            <fieldset class="row gx-3">
                                <legend>Dados Pessoais</legend>
                                <div class="form-floating mb-3">
                                    <input name="nome" class="form-control" type="text" value="<?= $this->view->usuario['nome'] ?>" autofocus />
                                    <label  for="txtNome">Nome</label>
                                </div>
                                <div class="form-floating mb-3 col-md-6 col-xl-4">
                                    <input class="form-control" type="text" id="txtCPF"  />
                                    <label for="txtCPF">CPF</label>
                                </div>
                                <div class="form-floating mb-3 col-md-6 col-xl-4">
                                    <input class="form-control" type="date" id="txtDataNascimento" placeholder=" " />
                                    <label for="txtDataNascimento" class="d-inline d-sm-none d-md-inline d-lg-none">Data
                                        Nascimento</label>
                                    <label for="txtDataNascimento" class="d-none d-sm-inline d-md-none d-lg-inline">Data
                                        de Nascimento</label>
                                </div>
                            </fieldset>
                            <fieldset>
                                <legend>Contatos</legend>
                                <div class="form-floating mb-3 col-md-8">
                                    <input  name="email" class="form-control" type="email"  value="<?= $this->view->usuario['email'] ?>" />
                                    <label for="txtEmail">E-mail</label>
                                </div>
                                <div class="form-floating mb-3 col-md-6">
                                    <input class="form-control" placeholder=" " type="text" id="txtTelefone" />
                                    <label for="txtTelefone">Telefone</label>
                                </div>
                            </fieldset>
                        </div>
                        <div class="col-sm-12 col-md-6">

                   
                            <fieldset class="row gx-3">
                                <legend>Endereço</legend>
                                <div class="form-floating mb-3 col-md-6 col-lg-4">
                                    <input value="<?=isset($this->view->dadosCEP['uf']) ? $this->view->dadosCEP['uf']:null?>" class="form-control" type="text" id="txtCEP" 
                                    placeholder=" "
                                    />
                                    <label for="txtCEP">Estado</label>
                                </div>
                                <div class="form-floating mb-3 col-md-8">
                                    <input  name ="CEP" class="form-control  bg-light"
                                    style="height: 58px; font-size: 14px;"
                                        />
                                       <label for="">Digite o CEP para buscarmos o endereço. </label>
                                        
                                </div>
                                <div class="clearfix"></div>
                                <div class="form-floating mb-3 col-md-4">
                                    <input class="form-control" type="text" id="txtNumero" placeholder=" " />
                                    <label for="txtNumero">Número</label>
                                </div>
                                <div class="form-floating mb-3 col-md-8">
                                    <input value="<?=isset($this->view->dadosCEP['logradouro']) ? $this->view->dadosCEP['logradouro']:null?>" class="form-control" type="text" id="txtComplemento" placeholder=" " />
                                    <label for="txtComplemento">Rua</label>
                                </div>
                                <div class="form-floating mb-3">
                                    <input value="<?=isset($this->view->dadosCEP['bairro']) ? $this->view->dadosCEP['bairro']:null?>" class="form-control" type="text" id="txtReferencia" placeholder=" " />
                                    <label for="txtReferencia">Bairro</label>
                                </div>
                                <button class=" btn btn-danger  " formaction='/cadastro' type="submit">Pesquisar CEP</button>
                           

                            </fieldset>
                       
                            <fieldset class="row gx-3">
                                <legend>Senha de Acesso</legend>
                                <div class="form-floating mb-3 col-lg-6">
                                    <input name="senha" class="form-control" type="password" id="txtSenha" value="<?= $this->view->usuario['senha'] ?>" />
                                    <label for="txtSenha">Senha</label>
                                </div>
                                <div class="form-floating mb-3 col-lg-6">
                                    <input class="form-control" id="txtConfirmacaoSenha" placeholder=" " />
                                    <label class="form-label" for="txtConfirmacaoSenha">Confirmação da Senha</label>
                                </div>
                            </fieldset>
                        </div>
                    </div>
                           
                    <hr />
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                        <label class="form-check-label" for="flexCheckDefault">
                            Desejo receber informações sobre promoções.
                        </label>
                    </div>
                    <div class="mb-3 text-left">

                        <a class="btn btn-lg btn-light btn-outline-danger" href="/">Cancelar</a>

                        <input type="button" onClick="enviaForm();" value="Criar meu cadastro" class="btn btn-lg btn-danger"
                             />
                    </div>
                    <script>
                        function enviaForm(){
                          
                           document.getElementById('form').action = '/registrar'
                           document.getElementById('form').submit();

                        }

                        function enviaForm2(){

                            document.getElementById('form2').action = '/cep';

                            document.getElementById('form2').submit();

                        }
                    </script>
                </form>
            </div>
        </main>

        <footer class="border-top text-muted bg-light">
            <div class="container">
                <div class="row py-3">
                    <div class="col-12 col-md-4 text-center text-md-left">
                        &copy; 2020 - Quitanda Online Ltda ME<br>
                        Rua Virtual Inexistente, 171, Compulândia/PC <br>
                        CPNJ 99.999.999/0001-99
                    </div>
                    <div class="col-12 col-md-4 text-center">
                        <a href="/privacidade.html" class="text-decoration-none text-dark">Política de
                            Privacidade</a><br>
                        <a href="/termos.html" class="text-decoration-none text-dark">Termos de Uso</a><br>
                        <a href="/quemsomos.html" class="text-decoration-none text-dark">Quem Somos</a><br>
                        <a href="/trocas.html" class="text-decoration-none text-dark">Trocas e Devoluções</a>
                    </div>
                    <div class="col-12 col-md-4 text-center text-md-right">
                        <a href="/contato.html" class="text-decoration-none text-dark">Contato pelo site</a><br>
                        E-mail: <a href="mailto:email@dominio.com"
                            class="text-decoration-none text-dark">email@dominio.com</a><br>
                        Telefone: <a href="phone:28999990000" class="text-decoration-none text-dark">(28) 99999-0000</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    