
 
        <main class="flex-fill mt-5">
            <div class="container">
                <h1 class="text-success">Sua Conta Foi Cadastrada Com Successo!</h1>
                <hr>
                <p>
                    Caro cliente,
                </p>
                <p>
                    Sua nova conta foi cadastrada com sucesso. Para entrar em sua área restrita agora mesmo, <a href="/timeline">clique aqui</a>.
                </p>
                <p>
                    Agradecemos pela confiança em nossos serviços.
                </p>
                <p>
                    Cordialmente,<br>
                    Central de Relacionamento Quitanda Online
                </p>
                <p>
                    <a href="/timeline" class="btn btn-lg btn-success">Voltar à Página Principal</a>
                </p>
            </div>
        </main>

        <footer class="border-top text-muted bg-light mt-5">
            <div class="container">
                <div class="row py-3">
                    <div class="col-12 col-md-4 text-center">
                        &copy; 2020 - Quitanda Online Ltda ME<br>
                        Rua Virtual Inexistente, 171, Compulândia/PC <br>
                        CPNJ 99.999.999/0001-99
                    </div>
                    <div class="col-12 col-md-4 text-center">
                        <a href="/privacidade.html" class="text-decoration-none text-dark">
                            Política de Privacidade
                        </a><br>
                        <a href="/termos.html" class="text-decoration-none text-dark">
                            Termos de Uso
                        </a><br>
                        <a href="/quemsomos.html" class="text-decoration-none text-dark">
                            Quem Somos
                        </a><br>
                        <a href="/trocas.html" class="text-decoration-none text-dark">
                            Trocas e Devoluções
                        </a>
                    </div>
                    <div class="col-12 col-md-4 text-center">
                        <a href="/contato.html" class="text-decoration-none text-dark">
                            Contato pelo Site
                        </a><br>
                        E-mail: <a href="mailto:email@dominio.com" class="text-decoration-none text-dark">
                            email@dominio.com
                        </a><br>
                        Telefone: <a href="phone:28999990000" class="text-decoration-none text-dark">
                            (28) 99999-0000
                        </a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    


