<div class="d-flex flex-column wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark bg-danger border-bottom shadow-sm mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="/adm"><b>Quitanda Online(ADM)</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" href="/adm">Principal</a>
                        </li>
                        
                    </ul>
                    <div class="align-self-end">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                            </li>

                            <li class="nav-item">
                                <a href="/sair" class="nav-link text-white me-5 ">sair</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        


        <section class="mt-5">

		<div class="container app">
			<div class="row">
				<div class="col-md-3 menu">
					<ul class="list-group">
						<li class="list-group-item active"><a href="#">Novo produto</a></li>
						<li class="list-group-item"><a href="/list_produto">Todos produtos</a></li>
					</ul>
				</div>

				<div class="col-md-9">
					<div class="container pagina">
						<div class="row">
							<div class="col">
								<h4>Novo Produto</h4>
								<hr />

								<form method="post" action="/salvaProdutos" enctype="multipart/form-data">
									<div class="form-group">
										<label>Nome do produto:</label>
										<input name="produto" type="text" class="form-control mb-3" placeholder="Exemplo: Abacate">

                                        <label>Foto do produto:</label>
                                        <input name="foto" type="file" class="form-control mb-3" placeholder="Exemplo: Abacate">

                                        <label>Descricao do produto:</label>
                                        <input name="descricao" type="text" class="form-control mb-3" placeholder="Exemplo: Produto de otima qualidade">

									</div>

									<button class="btn btn-danger">Cadastrar</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>


        </section>

        
        

      