<div class="d-flex flex-column wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark bg-danger border-bottom shadow-sm mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="/adm"><b>Quitanda Online(ADM)</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" href="/adm">Principal</a>
                        </li>
                        
                    </ul>
                    <div class="align-self-end">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                            </li>

                            <li class="nav-item">
                                <a href="/sair" class="nav-link text-white me-5 ">sair</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>



<div class="container app">
			<div class="row">
				<div class="col-sm-3 menu">
					<ul class="list-group">
						<li class="list-group-item"><a href="/area_adm">Novo produto</a></li>
						<li class="list-group-item active"><a href="#">Todos produtos</a></li>
					</ul>
				</div>

				<div class="col-sm-9">
					<div class="container pagina">
						<div class="row">
							<div class="col">
								<h4>Todos produtos</h4>
								<hr />

								<? foreach ($this->view->produtos as $id => $produto) {?>
									<div class="row mb-3 d-flex align-items-center tarefa">
									<div class="col-sm-9" id="tarefa_<?=$produto['id']?>">
                                        <tbody>
                                            <tr>
                                            <th scope="row"><?=$produto['id']?></th>
                                            <td><img height="100" src="<?=$produto['foto']?>" alt=""></td>
                                            <td><?=$produto['produto']?></td>
                                            

                                        </tbody>
									</div>
									<div class="col-sm-3 mt-2 d-flex justify-content-between">
									<a href="/deletar?acao=remover&id=<?=$produto['id']?>"><i class="fas fa-trash-alt fa-lg text-danger" onclick="remover(<?=$produto['id']?>)"></i></a>

									<i class="fas fa-edit fa-lg text-info" onclick="editar(<?=$produto['id']?>,'<?=$produto['produto']?>')"></i>
										
									</div>
								</div>
								
								<? }?>
						
									
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>